
/gate/verbose Physic   2 
/gate/verbose Cuts     2 
/gate/verbose SD       2 
/gate/verbose Actions  2 
/gate/verbose Actor    2 
/gate/verbose Step     2 
/gate/verbose Error    2 
/gate/verbose Warning  2 
/gate/verbose Output   2 
/gate/verbose Beam     2 
/gate/verbose Volume   2 
/gate/verbose Image    2 
/gate/verbose Geometry 2 
/gate/verbose Core     2 

/run/verbose 0
/event/verbose 0
/tracking/verbose 0	      

